/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as ApiQuotesRouteImport } from './routes/api.quotes'
import { Route as ApiPhotosRouteImport } from './routes/api.photos'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as EquipmentCategoryIndexRouteImport } from './routes/equipment.$category.index'
import { Route as EquipmentCategoryIdRouteImport } from './routes/equipment.$category.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesRoute = ApiQuotesRouteImport.update({
  id: '/api/quotes',
  path: '/api/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosRoute = ApiPhotosRouteImport.update({
  id: '/api/photos',
  path: '/api/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentCategoryIndexRoute = EquipmentCategoryIndexRouteImport.update({
  id: '/equipment/$category/',
  path: '/equipment/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentCategoryIdRoute = EquipmentCategoryIdRouteImport.update({
  id: '/equipment/$category/$id',
  path: '/equipment/$category/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/photos': typeof ApiPhotosRoute
  '/api/quotes': typeof ApiQuotesRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/equipment/$category/$id': typeof EquipmentCategoryIdRoute
  '/equipment/$category/': typeof EquipmentCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/photos': typeof ApiPhotosRoute
  '/api/quotes': typeof ApiQuotesRoute
  '/equipment': typeof EquipmentIndexRoute
  '/equipment/$category/$id': typeof EquipmentCategoryIdRoute
  '/equipment/$category': typeof EquipmentCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/photos': typeof ApiPhotosRoute
  '/api/quotes': typeof ApiQuotesRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/equipment/$category/$id': typeof EquipmentCategoryIdRoute
  '/equipment/$category/': typeof EquipmentCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/photos'
    | '/api/quotes'
    | '/equipment/'
    | '/equipment/$category/$id'
    | '/equipment/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/photos'
    | '/api/quotes'
    | '/equipment'
    | '/equipment/$category/$id'
    | '/equipment/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/photos'
    | '/api/quotes'
    | '/equipment/'
    | '/equipment/$category/$id'
    | '/equipment/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiPhotosRoute: typeof ApiPhotosRoute
  ApiQuotesRoute: typeof ApiQuotesRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
  EquipmentCategoryIdRoute: typeof EquipmentCategoryIdRoute
  EquipmentCategoryIndexRoute: typeof EquipmentCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes': {
      id: '/api/quotes'
      path: '/api/quotes'
      fullPath: '/api/quotes'
      preLoaderRoute: typeof ApiQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos': {
      id: '/api/photos'
      path: '/api/photos'
      fullPath: '/api/photos'
      preLoaderRoute: typeof ApiPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$category/': {
      id: '/equipment/$category/'
      path: '/equipment/$category'
      fullPath: '/equipment/$category/'
      preLoaderRoute: typeof EquipmentCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$category/$id': {
      id: '/equipment/$category/$id'
      path: '/equipment/$category/$id'
      fullPath: '/equipment/$category/$id'
      preLoaderRoute: typeof EquipmentCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  ApiPhotosRoute: ApiPhotosRoute,
  ApiQuotesRoute: ApiQuotesRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
  EquipmentCategoryIdRoute: EquipmentCategoryIdRoute,
  EquipmentCategoryIndexRoute: EquipmentCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
